### ISSUE TITLE
下载下来，运行报错。

### ISSUE THREAD

**Issue by developerjet** [coderMyy/CocoaAsyncSocket_Demo#11]
你好，请问为什么下载下来，运行报错啊。

**Comment by coderMyy** [comment]
不会啊。

________________________________
发件人: CoderTan <notifications@github.com>
发送时间: 2017年10月11日 16:55:52
收件人: coderMyy/CocoaAsyncSocket_Demo
抄送: Subscribed
主题: [coderMyy/CocoaAsyncSocket_Demo] 下载下来，运行报错。 (#11)


你好，请问为什么下载下来，运行报错啊。

―
